--------------------------------------------------------
--  File created - Thursday-April-04-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_ALERTA_SEGURIDAD
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_ALERTA_SEGURIDAD" 
   (	"ID_ALERTA" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"GRAVEDAD" VARCHAR2(15 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_BRANCH
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_BRANCH" 
   (	"ID_BRANCH" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_COLABORADORES
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_COLABORADORES" 
   (	"ID_COLABORADOR" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"NIVEL_PERMISO" VARCHAR2(15 BYTE), 
	"FECHA_UNION" DATE, 
	"ULTIMA_FECHA_ACCESO" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"COMENTARIOS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_COMENTARIOS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_COMENTARIOS" 
   (	"ID_COMENTARIO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"FECHA_COMENTARIO" DATE, 
	"COMENTARIO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_COMMITS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_COMMITS" 
   (	"ID_COMMIT" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"COMMIT_MESSAGE" VARCHAR2(100 BYTE), 
	"COMMIT_DATE" DATE, 
	"CHANGES_COUNT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CONFIG_ACCESO_REPOSITORIO
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" 
   (	"ID_CONFIGURACION" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"TIPO_ACCESO" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CONTRIBUIDORES
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" 
   (	"ID_CONTRIBUIDOR" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"CANTIDAD_CONTRIBUICIONES" NUMBER(*,0), 
	"DATE_FIRST_CTRB" DATE, 
	"DATE_LAST_CTRB" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DEPLOYMENT
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_DEPLOYMENT" 
   (	"ID_DEPLOY" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"ENTORNO" VARCHAR2(20 BYTE), 
	"DATE_DEPLOY" DATE, 
	"STATUS" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DISCUSSION
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_DISCUSSION" 
   (	"ID_DISCUSION" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"TITULO" VARCHAR2(15 BYTE), 
	"CONTENIDO" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_DISCUSS_COMMENT
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" 
   (	"ID_COMENTARIO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_DISCUSION" NUMBER(*,0), 
	"CONTENIDO" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_EQUIPO
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_EQUIPO" 
   (	"ID_EQUIPO" NUMBER(*,0), 
	"ID_ORGANIZACION" NUMBER(*,0), 
	"NOMBRE_EQUIPO" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_FILE
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_FILE" 
   (	"ID_FILE" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"NOMBRE_ARCHIVO" VARCHAR2(20 BYTE), 
	"EXTENSION" VARCHAR2(20 BYTE), 
	"TAMANIO" NUMBER(*,0), 
	"DATE_LAST_MODIF" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_FILE_MODIF
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_FILE_MODIF" 
   (	"ID_MODIFICATION" NUMBER(*,0), 
	"ID_COMMIT" NUMBER(*,0), 
	"FILE_PATH" VARCHAR2(50 BYTE), 
	"LINES_ADDED" VARCHAR2(100 BYTE), 
	"LINES_DELETED" VARCHAR2(120 BYTE), 
	"MODIF_TYPE" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_GIST
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_GIST" 
   (	"ID_GIST" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"DESCRIPTION_GIST" VARCHAR2(100 BYTE), 
	"FECHA_CREATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ISSUES
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_ISSUES" 
   (	"ID_ISSUES" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"TITULO_ISSUE" VARCHAR2(20 BYTE), 
	"DESCRIPCION_ISSUE" VARCHAR2(100 BYTE), 
	"ESTADO_ISSUE" VARCHAR2(20 BYTE), 
	"FECHA_CREACION_ISSUE" DATE, 
	"FECHA_CIERRE_ISSUE" DATE, 
	"ULTIMA_FECHA_ACTUALIZACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_LABELS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_LABELS" 
   (	"ID_LABEL" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRPTION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_ULT_ACT" DATE, 
	"NIVEL_PRIORIDAD" VARCHAR2(15 BYTE), 
	"RESTRCCIONES" VARCHAR2(100 BYTE), 
	"SCOPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MIEMBRO_EQUIPO
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_MIEMBRO_EQUIPO" 
   (	"ID_MIEMBRO" NUMBER(*,0), 
	"ID_EQUIPO" NUMBER(*,0), 
	"ROL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_MILESTONES
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_MILESTONES" 
   (	"ID_MILESTONE" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"TITTLE_MILESTONE" VARCHAR2(20 BYTE), 
	"DESCRIPTION_MILESTONE" VARCHAR2(30 BYTE), 
	"DUE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ORGANIZACION
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_ORGANIZACION" 
   (	"ID_ORGANIZACION" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE), 
	"FECHA_CREACION" DATE, 
	"LOCACION" VARCHAR2(200 BYTE), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"NUMERO_MIEMBROS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PROYECTOS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_PROYECTOS" 
   (	"ID_PROYECTO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DESCRIPTION_PROYECTO" VARCHAR2(100 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PULL_REQUEST
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_PULL_REQUEST" 
   (	"ID_PULL_REQUEST" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"TITULO" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"ESTADO" VARCHAR2(200 BYTE), 
	"FECHA_CREACION" DATE, 
	"FECHA_CIERRE" DATE, 
	"FECHA_MERGE" DATE, 
	"RAMA_BASE" VARCHAR2(200 BYTE), 
	"NUMERO_COMMITS" NUMBER(*,0), 
	"REVIEW_STATUS" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_REGISTRO_PAQUETES
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_REGISTRO_PAQUETES" 
   (	"ID_REGISTRO" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"NOMBRE_PAQUETE" VARCHAR2(20 BYTE), 
	"VERSION_PAQUETE" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_REPOSITORIO
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_REPOSITORIO" 
   (	"ID_REPOSITORIO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE_REPOSITORIO" VARCHAR2(50 BYTE), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"FECHA_CREACION_REPOSITORIO" DATE, 
	"FECHA_ULTIMA_ACTUALIZACION" DATE, 
	"NUMERO_ESTRELLAS" NUMBER(*,0), 
	"NUMERO_FORKS" NUMBER(*,0), 
	"LENGUAJE_PRINCIPAL" VARCHAR2(20 BYTE), 
	"CANTIDAD_PULLS" NUMBER(*,0), 
	"CANTIDAD_ISSUES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SECRETOS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_SECRETOS" 
   (	"ID_SECRETS" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"VALOR" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SEGUIDORES
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_SEGUIDORES" 
   (	"ID_SEGUIDOR" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"FECHA_SEGUIDO" DATE, 
	"VISIBILIDAD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SPONSOR_ELEGIBLE
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_SPONSOR_ELEGIBLE" 
   (	"ID_SPONSOR_ELEGIBLE" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SPONSOR_OTROS_USERS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" 
   (	"ID_SPONSOR_OTROS" NUMBER(*,0), 
	"ID_PROYECTO" NUMBER(*,0), 
	"LISTA_SPONSOR" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_SPONSOR_PROPIO
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" 
   (	"ID_SPONSOR_PROPIO" NUMBER(*,0), 
	"ID_SPONSOR_ELEGIBLE" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_STARS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_STARS" 
   (	"ID_ESTRELLA" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"FECHA_ESTRELLA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TAGS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_TAGS" 
   (	"ID_TAG" NUMBER(*,0), 
	"ID_REPOSITORIO" NUMBER(*,0), 
	"TITULO" VARCHAR2(20 BYTE), 
	"CONTENIDO" VARCHAR2(40 BYTE), 
	"FECHA_CREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIOS
--------------------------------------------------------

  CREATE TABLE "C##GITHUB"."TBL_USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"CORREO" VARCHAR2(40 BYTE), 
	"CONTRASENIA" VARCHAR2(20 BYTE), 
	"FECHA_CREACION" DATE, 
	"UBICACION" VARCHAR2(30 BYTE), 
	"BIOGRAFIA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALERTA_SEGURIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."ALERTA_SEGURIDAD" ON "C##GITHUB"."TBL_ALERTA_SEGURIDAD" ("ID_ALERTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COLABORADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."COLABORADORES_PK" ON "C##GITHUB"."TBL_COLABORADORES" ("ID_COLABORADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONFIG_ACCESO_REPOSITORIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."CONFIG_ACCESO_REPOSITORIO" ON "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" ("ID_CONFIGURACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_BRANCH_PK" ON "C##GITHUB"."TBL_BRANCH" ("ID_BRANCH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_COMENTARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_COMENTARIOS_PK" ON "C##GITHUB"."TBL_COMENTARIOS" ("ID_COMENTARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_COMMITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_COMMITS_PK" ON "C##GITHUB"."TBL_COMMITS" ("ID_COMMIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CONTRIBUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_CONTRIBUIDORES_PK" ON "C##GITHUB"."TBL_CONTRIBUIDORES" ("ID_CONTRIBUIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CONTRIBUIDORES__UNV2
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_CONTRIBUIDORES__UNV2" ON "C##GITHUB"."TBL_CONTRIBUIDORES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DEPLOYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_DEPLOYMENT_PK" ON "C##GITHUB"."TBL_DEPLOYMENT" ("ID_DEPLOY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DISCUSSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_DISCUSSION_PK" ON "C##GITHUB"."TBL_DISCUSSION" ("ID_DISCUSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DISCUSS_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_DISCUSS_COMMENT_PK" ON "C##GITHUB"."TBL_DISCUSS_COMMENT" ("ID_COMENTARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_EQUIPO_PK" ON "C##GITHUB"."TBL_EQUIPO" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_FILE_MODIF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_FILE_MODIF_PK" ON "C##GITHUB"."TBL_FILE_MODIF" ("ID_MODIFICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_FILE_PK" ON "C##GITHUB"."TBL_FILE" ("ID_FILE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_GIST_PK" ON "C##GITHUB"."TBL_GIST" ("ID_GIST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ISSUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_ISSUES_PK" ON "C##GITHUB"."TBL_ISSUES" ("ID_ISSUES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_LABELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_LABELS_PK" ON "C##GITHUB"."TBL_LABELS" ("ID_LABEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MIEMBRO_EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_MIEMBRO_EQUIPO_PK" ON "C##GITHUB"."TBL_MIEMBRO_EQUIPO" ("ID_MIEMBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MILESTONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_MILESTONES_PK" ON "C##GITHUB"."TBL_MILESTONES" ("ID_MILESTONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ORGANIZACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_ORGANIZACION_PK" ON "C##GITHUB"."TBL_ORGANIZACION" ("ID_ORGANIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PROYECTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_PROYECTOS_PK" ON "C##GITHUB"."TBL_PROYECTOS" ("ID_PROYECTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PULL_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_PULL_REQUEST_PK" ON "C##GITHUB"."TBL_PULL_REQUEST" ("ID_PULL_REQUEST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REGISTRO_PAQUETES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_REGISTRO_PAQUETES_PK" ON "C##GITHUB"."TBL_REGISTRO_PAQUETES" ("ID_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REPOSITORIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_REPOSITORIO_PK" ON "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SECRETOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SECRETOS_PK" ON "C##GITHUB"."TBL_SECRETOS" ("ID_SECRETS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SEGUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SEGUIDORES_PK" ON "C##GITHUB"."TBL_SEGUIDORES" ("ID_SEGUIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SPONSOR_ELEGIBLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SPONSOR_ELEGIBLE_PK" ON "C##GITHUB"."TBL_SPONSOR_ELEGIBLE" ("ID_SPONSOR_ELEGIBLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SPONSOR_OTROS_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SPONSOR_OTROS_USERS_PK" ON "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" ("ID_SPONSOR_OTROS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SPONSOR_PROPIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SPONSOR_PROPIO_PK" ON "C##GITHUB"."TBL_SPONSOR_PROPIO" ("ID_SPONSOR_PROPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_STARS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_STARS_PK" ON "C##GITHUB"."TBL_STARS" ("ID_ESTRELLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_TAG_PK" ON "C##GITHUB"."TBL_TAGS" ("ID_TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."USUARIOS_PK" ON "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ALERTA_SEGURIDAD
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."ALERTA_SEGURIDAD" ON "C##GITHUB"."TBL_ALERTA_SEGURIDAD" ("ID_ALERTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_BRANCH_PK" ON "C##GITHUB"."TBL_BRANCH" ("ID_BRANCH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COLABORADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."COLABORADORES_PK" ON "C##GITHUB"."TBL_COLABORADORES" ("ID_COLABORADOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_COMENTARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_COMENTARIOS_PK" ON "C##GITHUB"."TBL_COMENTARIOS" ("ID_COMENTARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_COMMITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_COMMITS_PK" ON "C##GITHUB"."TBL_COMMITS" ("ID_COMMIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONFIG_ACCESO_REPOSITORIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."CONFIG_ACCESO_REPOSITORIO" ON "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" ("ID_CONFIGURACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CONTRIBUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_CONTRIBUIDORES_PK" ON "C##GITHUB"."TBL_CONTRIBUIDORES" ("ID_CONTRIBUIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CONTRIBUIDORES__UNV2
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_CONTRIBUIDORES__UNV2" ON "C##GITHUB"."TBL_CONTRIBUIDORES" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DEPLOYMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_DEPLOYMENT_PK" ON "C##GITHUB"."TBL_DEPLOYMENT" ("ID_DEPLOY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DISCUSSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_DISCUSSION_PK" ON "C##GITHUB"."TBL_DISCUSSION" ("ID_DISCUSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_DISCUSS_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_DISCUSS_COMMENT_PK" ON "C##GITHUB"."TBL_DISCUSS_COMMENT" ("ID_COMENTARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_EQUIPO_PK" ON "C##GITHUB"."TBL_EQUIPO" ("ID_EQUIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_FILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_FILE_PK" ON "C##GITHUB"."TBL_FILE" ("ID_FILE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_FILE_MODIF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_FILE_MODIF_PK" ON "C##GITHUB"."TBL_FILE_MODIF" ("ID_MODIFICATION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_GIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_GIST_PK" ON "C##GITHUB"."TBL_GIST" ("ID_GIST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ISSUES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_ISSUES_PK" ON "C##GITHUB"."TBL_ISSUES" ("ID_ISSUES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_LABELS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_LABELS_PK" ON "C##GITHUB"."TBL_LABELS" ("ID_LABEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MIEMBRO_EQUIPO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_MIEMBRO_EQUIPO_PK" ON "C##GITHUB"."TBL_MIEMBRO_EQUIPO" ("ID_MIEMBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_MILESTONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_MILESTONES_PK" ON "C##GITHUB"."TBL_MILESTONES" ("ID_MILESTONE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ORGANIZACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_ORGANIZACION_PK" ON "C##GITHUB"."TBL_ORGANIZACION" ("ID_ORGANIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PROYECTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_PROYECTOS_PK" ON "C##GITHUB"."TBL_PROYECTOS" ("ID_PROYECTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PULL_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_PULL_REQUEST_PK" ON "C##GITHUB"."TBL_PULL_REQUEST" ("ID_PULL_REQUEST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REGISTRO_PAQUETES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_REGISTRO_PAQUETES_PK" ON "C##GITHUB"."TBL_REGISTRO_PAQUETES" ("ID_REGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_REPOSITORIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_REPOSITORIO_PK" ON "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SECRETOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SECRETOS_PK" ON "C##GITHUB"."TBL_SECRETOS" ("ID_SECRETS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SEGUIDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SEGUIDORES_PK" ON "C##GITHUB"."TBL_SEGUIDORES" ("ID_SEGUIDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SPONSOR_ELEGIBLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SPONSOR_ELEGIBLE_PK" ON "C##GITHUB"."TBL_SPONSOR_ELEGIBLE" ("ID_SPONSOR_ELEGIBLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SPONSOR_OTROS_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SPONSOR_OTROS_USERS_PK" ON "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" ("ID_SPONSOR_OTROS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_SPONSOR_PROPIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_SPONSOR_PROPIO_PK" ON "C##GITHUB"."TBL_SPONSOR_PROPIO" ("ID_SPONSOR_PROPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_STARS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_STARS_PK" ON "C##GITHUB"."TBL_STARS" ("ID_ESTRELLA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TAG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."TBL_TAG_PK" ON "C##GITHUB"."TBL_TAGS" ("ID_TAG") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##GITHUB"."USUARIOS_PK" ON "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_ALERTA_SEGURIDAD
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_ALERTA_SEGURIDAD" MODIFY ("ID_ALERTA" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_ALERTA_SEGURIDAD" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_ALERTA_SEGURIDAD" ADD CONSTRAINT "ALERTA_SEGURIDAD" PRIMARY KEY ("ID_ALERTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_BRANCH
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_BRANCH" MODIFY ("ID_BRANCH" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_BRANCH" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_BRANCH" ADD CONSTRAINT "TBL_BRANCH_PK" PRIMARY KEY ("ID_BRANCH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_COLABORADORES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_COLABORADORES" MODIFY ("ID_COLABORADOR" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COLABORADORES" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COLABORADORES" ADD CONSTRAINT "COLABORADORES_PK" PRIMARY KEY ("ID_COLABORADOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_COMENTARIOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_COMENTARIOS" MODIFY ("ID_COMENTARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COMENTARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COMENTARIOS" ADD CONSTRAINT "TBL_COMENTARIOS_PK" PRIMARY KEY ("ID_COMENTARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_COMMITS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_COMMITS" MODIFY ("ID_COMMIT" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COMMITS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COMMITS" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_COMMITS" ADD CONSTRAINT "TBL_COMMITS_PK" PRIMARY KEY ("ID_COMMIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CONFIG_ACCESO_REPOSITORIO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" MODIFY ("ID_CONFIGURACION" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" ADD CONSTRAINT "CONFIG_ACCESO_REPOSITORIO" PRIMARY KEY ("ID_CONFIGURACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_CONTRIBUIDORES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" MODIFY ("ID_CONTRIBUIDOR" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" ADD CONSTRAINT "TBL_CONTRIBUIDORES_PK" PRIMARY KEY ("ID_CONTRIBUIDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" ADD CONSTRAINT "TBL_CONTRIBUIDORES__UNV2" UNIQUE ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DEPLOYMENT
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_DEPLOYMENT" MODIFY ("ID_DEPLOY" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DEPLOYMENT" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DEPLOYMENT" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DEPLOYMENT" ADD CONSTRAINT "TBL_DEPLOYMENT_PK" PRIMARY KEY ("ID_DEPLOY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DISCUSSION
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_DISCUSSION" MODIFY ("ID_DISCUSION" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DISCUSSION" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DISCUSSION" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DISCUSSION" ADD CONSTRAINT "TBL_DISCUSSION_PK" PRIMARY KEY ("ID_DISCUSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_DISCUSS_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" MODIFY ("ID_COMENTARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" MODIFY ("ID_DISCUSION" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" ADD CONSTRAINT "TBL_DISCUSS_COMMENT_PK" PRIMARY KEY ("ID_COMENTARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_EQUIPO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_EQUIPO" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_EQUIPO" MODIFY ("ID_ORGANIZACION" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_EQUIPO" ADD CONSTRAINT "TBL_EQUIPO_PK" PRIMARY KEY ("ID_EQUIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_FILE
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_FILE" MODIFY ("ID_FILE" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_FILE" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_FILE" ADD CONSTRAINT "TBL_FILE_PK" PRIMARY KEY ("ID_FILE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_FILE_MODIF
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_FILE_MODIF" MODIFY ("ID_MODIFICATION" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_FILE_MODIF" MODIFY ("ID_COMMIT" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_FILE_MODIF" ADD CONSTRAINT "TBL_FILE_MODIF_PK" PRIMARY KEY ("ID_MODIFICATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_GIST
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_GIST" MODIFY ("ID_GIST" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_GIST" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_GIST" ADD CONSTRAINT "TBL_GIST_PK" PRIMARY KEY ("ID_GIST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ISSUES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_ISSUES" MODIFY ("ID_ISSUES" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_ISSUES" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_ISSUES" ADD CONSTRAINT "TBL_ISSUES_PK" PRIMARY KEY ("ID_ISSUES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_LABELS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_LABELS" MODIFY ("ID_LABEL" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_LABELS" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_LABELS" ADD CONSTRAINT "TBL_LABELS_PK" PRIMARY KEY ("ID_LABEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_MIEMBRO_EQUIPO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_MIEMBRO_EQUIPO" MODIFY ("ID_MIEMBRO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_MIEMBRO_EQUIPO" MODIFY ("ID_EQUIPO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_MIEMBRO_EQUIPO" ADD CONSTRAINT "TBL_MIEMBRO_EQUIPO_PK" PRIMARY KEY ("ID_MIEMBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_MILESTONES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_MILESTONES" MODIFY ("ID_MILESTONE" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_MILESTONES" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_MILESTONES" ADD CONSTRAINT "TBL_MILESTONES_PK" PRIMARY KEY ("ID_MILESTONE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_ORGANIZACION" MODIFY ("ID_ORGANIZACION" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_ORGANIZACION" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_ORGANIZACION" ADD CONSTRAINT "TBL_ORGANIZACION_PK" PRIMARY KEY ("ID_ORGANIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PROYECTOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_PROYECTOS" MODIFY ("ID_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_PROYECTOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_PROYECTOS" ADD CONSTRAINT "TBL_PROYECTOS_PK" PRIMARY KEY ("ID_PROYECTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_PULL_REQUEST
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_PULL_REQUEST" MODIFY ("ID_PULL_REQUEST" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_PULL_REQUEST" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_PULL_REQUEST" ADD CONSTRAINT "TBL_PULL_REQUEST_PK" PRIMARY KEY ("ID_PULL_REQUEST")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_REGISTRO_PAQUETES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_REGISTRO_PAQUETES" MODIFY ("ID_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_REGISTRO_PAQUETES" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_REGISTRO_PAQUETES" ADD CONSTRAINT "TBL_REGISTRO_PAQUETES_PK" PRIMARY KEY ("ID_REGISTRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_REPOSITORIO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_REPOSITORIO" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_REPOSITORIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_REPOSITORIO" ADD CONSTRAINT "TBL_REPOSITORIO_PK" PRIMARY KEY ("ID_REPOSITORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SECRETOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SECRETOS" MODIFY ("ID_SECRETS" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SECRETOS" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SECRETOS" ADD CONSTRAINT "TBL_SECRETOS_PK" PRIMARY KEY ("ID_SECRETS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SEGUIDORES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SEGUIDORES" MODIFY ("ID_SEGUIDOR" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SEGUIDORES" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SEGUIDORES" ADD CONSTRAINT "TBL_SEGUIDORES_PK" PRIMARY KEY ("ID_SEGUIDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SPONSOR_ELEGIBLE
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_ELEGIBLE" MODIFY ("ID_SPONSOR_ELEGIBLE" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_ELEGIBLE" ADD CONSTRAINT "TBL_SPONSOR_ELEGIBLE_PK" PRIMARY KEY ("ID_SPONSOR_ELEGIBLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SPONSOR_OTROS_USERS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" MODIFY ("ID_SPONSOR_OTROS" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" MODIFY ("ID_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" ADD CONSTRAINT "TBL_SPONSOR_OTROS_USERS_PK" PRIMARY KEY ("ID_SPONSOR_OTROS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_SPONSOR_PROPIO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" MODIFY ("ID_SPONSOR_PROPIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" MODIFY ("ID_SPONSOR_ELEGIBLE" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" ADD CONSTRAINT "TBL_SPONSOR_PROPIO_PK" PRIMARY KEY ("ID_SPONSOR_PROPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_STARS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_STARS" MODIFY ("ID_ESTRELLA" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_STARS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_STARS" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_STARS" ADD CONSTRAINT "TBL_STARS_PK" PRIMARY KEY ("ID_ESTRELLA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_TAGS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_TAGS" MODIFY ("ID_TAG" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_TAGS" MODIFY ("ID_REPOSITORIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_TAGS" ADD CONSTRAINT "TBL_TAG_PK" PRIMARY KEY ("ID_TAG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TBL_USUARIOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "C##GITHUB"."TBL_USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ALERTA_SEGURIDAD
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_ALERTA_SEGURIDAD" ADD CONSTRAINT "TBL_ALERTA_SEGURIDAD" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_BRANCH
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_BRANCH" ADD CONSTRAINT "TBL_BRANCH_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_COLABORADORES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_COLABORADORES" ADD CONSTRAINT "TBL_COLABORADORES" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_COMENTARIOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_COMENTARIOS" ADD CONSTRAINT "TBL_COMENTARIOS_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_COMMITS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_COMMITS" ADD CONSTRAINT "TBL_COMMITS_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_COMMITS" ADD CONSTRAINT "TBL_COMMITS_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CONFIG_ACCESO_REPOSITORIO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_CONFIG_ACCESO_REPOSITORIO" ADD CONSTRAINT "CONFIG_ACCESO_REPOSITORIOV2" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_CONTRIBUIDORES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" ADD CONSTRAINT "CONTRIBUIDORES_REPOSITORIO" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_CONTRIBUIDORES" ADD CONSTRAINT "CONTRIBUIDORES_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DEPLOYMENT
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_DEPLOYMENT" ADD CONSTRAINT "DEPLOYMENT_REPOSITORIO" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_DEPLOYMENT" ADD CONSTRAINT "DEPLOYMENT_USUARIOS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DISCUSSION
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_DISCUSSION" ADD CONSTRAINT "DISCUSSION_REPOSITORIO" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_DISCUSSION" ADD CONSTRAINT "DISCUSSION_USUARIOS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_DISCUSS_COMMENT
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" ADD CONSTRAINT "DISCUSS_COMMENT" FOREIGN KEY ("ID_DISCUSION")
	  REFERENCES "C##GITHUB"."TBL_DISCUSSION" ("ID_DISCUSION") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_DISCUSS_COMMENT" ADD CONSTRAINT "DISCUSS_COMMENT_USUARIOS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_EQUIPO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_EQUIPO" ADD CONSTRAINT "TBL_EQUIPO_TBL_ORGANIZACION_FK" FOREIGN KEY ("ID_ORGANIZACION")
	  REFERENCES "C##GITHUB"."TBL_ORGANIZACION" ("ID_ORGANIZACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_FILE
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_FILE" ADD CONSTRAINT "TBL_FILE_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_FILE_MODIF
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_FILE_MODIF" ADD CONSTRAINT "TBL_FILE_MODIF_TBL_COMMITS_FK" FOREIGN KEY ("ID_COMMIT")
	  REFERENCES "C##GITHUB"."TBL_COMMITS" ("ID_COMMIT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_GIST
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_GIST" ADD CONSTRAINT "TBL_GIST_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ISSUES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_ISSUES" ADD CONSTRAINT "TBL_ISSUES_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_LABELS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_LABELS" ADD CONSTRAINT "TBL_LABELS_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_MIEMBRO_EQUIPO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_MIEMBRO_EQUIPO" ADD CONSTRAINT "MIEMBRO_EQUIPO" FOREIGN KEY ("ID_EQUIPO")
	  REFERENCES "C##GITHUB"."TBL_EQUIPO" ("ID_EQUIPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_MILESTONES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_MILESTONES" ADD CONSTRAINT "TBL_MILESTONES" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_ORGANIZACION
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_ORGANIZACION" ADD CONSTRAINT "TBL_ORGANIZACION_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PROYECTOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_PROYECTOS" ADD CONSTRAINT "TBL_PROYECTOS_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PULL_REQUEST
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_PULL_REQUEST" ADD CONSTRAINT "PULL_REQUEST" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_REGISTRO_PAQUETES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_REGISTRO_PAQUETES" ADD CONSTRAINT "TBL_REGISTRO_PAQUETES" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_REPOSITORIO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_REPOSITORIO" ADD CONSTRAINT "TBL_REPOSITORIO_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SECRETOS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SECRETOS" ADD CONSTRAINT "TBL_SECRETOS" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SEGUIDORES
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SEGUIDORES" ADD CONSTRAINT "TBL_SEGUIDORES_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SPONSOR_OTROS_USERS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_OTROS_USERS" ADD CONSTRAINT "TBL_SPONSOR_OTROS_USERS" FOREIGN KEY ("ID_PROYECTO")
	  REFERENCES "C##GITHUB"."TBL_PROYECTOS" ("ID_PROYECTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_SPONSOR_PROPIO
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" ADD CONSTRAINT "TBL_SPONSOR_PROPIO" FOREIGN KEY ("ID_SPONSOR_ELEGIBLE")
	  REFERENCES "C##GITHUB"."TBL_SPONSOR_ELEGIBLE" ("ID_SPONSOR_ELEGIBLE") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_SPONSOR_PROPIO" ADD CONSTRAINT "TBL_SPONSOR_PROPIO_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_STARS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_STARS" ADD CONSTRAINT "TBL_STARS_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
  ALTER TABLE "C##GITHUB"."TBL_STARS" ADD CONSTRAINT "TBL_STARS_USUARIOS_FK" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "C##GITHUB"."TBL_USUARIOS" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_TAGS
--------------------------------------------------------

  ALTER TABLE "C##GITHUB"."TBL_TAGS" ADD CONSTRAINT "TBL_TAG_TBL_REPOSITORIO_FK" FOREIGN KEY ("ID_REPOSITORIO")
	  REFERENCES "C##GITHUB"."TBL_REPOSITORIO" ("ID_REPOSITORIO") ENABLE;
